[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
include_trailing_comma = true
multi_line_output = 3

[tool.flake8]
max-line-length = 88
ignore = "E203,W503"
max-complexity = 10
exclude = ".git,__pycache__,build,dist,.venv"

[tool.coverage.run]
branch = true
omit = ["tests/*", "docs/*"]
